### PR TITLE
Add sass styleguide

### PR DESCRIPTION
**Pull request by peyerluk**

### CODE REVIEW

**Comment by peyerluk** [comment]
@rawdiggie please extend and review

**Comment by rawdiggie** [comment]
Yeah, thx for taking the first step. :dancers:  

Tomorrow I’ll take some time for making this up.

**Comment by masone** [comment]
Is this mergable? If it's deprecated by now, please close the pr.

**Comment by rawdiggie** [comment]
I’ll merge this for now. Later this month I’ll spend a few hours to adjust and extend it a little bit.

**Comment by rawdiggie** [comment]
@fliptation You can help me with this of if you like.

**Pull request merged**
